export enum ErrorCode {
  MONGODB_ERROR = 'MONGODB_ERROR',
  AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
  AUTH_INVALID_PASSWORD_OR_USERNAME = 'AUTH_INVALID_PASSWORD_OR_USERNAME',
  AUTH_EXCEED_RETRY_PASSWORD_MAXIMUM = 'AUTH_EXCEED_RETRY_PASSWORD_MAXIMUM',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTED = 'USER_ALREADY_EXISTED',
  ACCESS_CODE_INVALID = 'ACCESS_CODE_INVALID',
}
